import Head from "next/head";
import styles from "../styles/Home.module.css";
import { Footer } from "../components/Footer";
import { Main } from "../components/Main";

//積極的にuseCollbackとuseMemoを使っていこう。
//アロー関数に書き換える
const Home = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main></Main>
      <Footer></Footer>
    </div>
  );
};
export default Home;
